version: "3"
services:
  react-app:
    # stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src:ro
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_NAME=reactApp1
    # env_file:
    #   - ./.env